name: Terraform CI/CD with Auto Teardown

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terra-config

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Wait for instance startup
        run: |
          echo "⏳ Waiting 240s for instance and app startup..."
          sleep 240

      - name: Fetch Public IP
        id: ec2_ip
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Health Check App
        run: |
          echo "🔍 Checking app at http://${{ steps.ec2_ip.outputs.public_ip }}"
          curl -f http://${{ steps.ec2_ip.outputs.public_ip }} || (echo "App not responding" && exit 1)

      - name: Keep App Running
        run: |
          echo "⏳ Keeping app alive for 5 minutes..."
          echo "Application is running at: http://${{ steps.ec2_ip.outputs.public_ip }}"
          sleep 300

      - name: Terraform Destroy
        if: always()
        run: terraform destroy -auto-approve
